name: deploy-game

on:
  push:
    branches:
      - main

jobs:
  deploy-live-document:
    runs-on: ubuntu-latest
    steps:
      # Step 1
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      # Step 2
      - name: Install wasm32-unknown-uknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Install trunk
        run: cargo install trunk
      - name: Build yew app with trunk
        run: trunk build --release
        env:
          SIGNALING_SERVER_URL: ${{ secrets.SIGNALING_SERVER_URL }}
          STUN_SERVER_URLS: ${{ secrets.STUN_SERVER_URLS }}
          TURN_SERVER_URLS: ${{ secrets.TURN_SERVER_URLS }}
          TURN_SERVER_USERNAME: ${{ secrets.TURN_SERVER_USERNAME }}
          TURN_SERVER_CREDENTIAL: ${{ secrets.TURN_SERVER_CREDENTIAL }}
      - name: Add as job artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./dist/ s3://wasm-peers-footballers --delete --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          VERBOSE: TRUE